<?php
require_once __DIR__.'/attendance.php';

// $start = $_POST['start_date'] ?? '';
// $end   = $_POST['end_date'] ?? '';

// if ($start === '' || $end === '') {
//     throw new RuntimeException('Start date and end date are required.');
// }

// if ($end < $start) {
//     throw new RuntimeException('End date cannot be before start date.');
// }

function oecrm_leave_policy($conn,$companyId,$leaveTypeId){$stmt=mysqli_prepare($conn,'SELECT p.*,s.comp_off_expiry_days,s.minimum_comp_off_minutes,s.sandwich_enabled company_sandwich FROM leave_policies p JOIN leave_settings s ON s.company_id=p.company_id WHERE p.company_id=? AND p.leave_type_id=? AND p.status=1');mysqli_stmt_bind_param($stmt,'ii',$companyId,$leaveTypeId);mysqli_stmt_execute($stmt);$r=mysqli_fetch_assoc(mysqli_stmt_get_result($stmt));mysqli_stmt_close($stmt);return $r;}
function oecrm_leave_calculate($conn,$employeeId,$leaveTypeId,$start,$end,$halfDay=false){$employee=mysqli_fetch_assoc(mysqli_query($conn,'SELECT company_id FROM employeestbl WHERE id='.(int)$employeeId));if(!$employee)throw new RuntimeException('Employee not found.');$policy=oecrm_leave_policy($conn,$employee['company_id'],$leaveTypeId);if(!$policy)throw new RuntimeException('Leave policy not configured.');$from=new DateTime($start);$to=new DateTime($end);if($to<$from)throw new RuntimeException('End date must be after start date.');$calendar=0;$working=0;$offInside=0;$cursor=clone $from;while($cursor<=$to){$date=$cursor->format('Y-m-d');$shift=oecrm_employee_shift($conn,$employeeId,$date);$off=$shift?oecrm_shift_is_weekly_off($conn,$shift['id'],$date):false;$holiday=oecrm_is_holiday($conn,$date,(int)$employee['company_id']);$calendar++;if($off||$holiday)$offInside++;else $working++;$cursor->modify('+1 day');}$sandwich=(!empty($policy['sandwich_enabled'])&&!empty($policy['company_sandwich'])&&$working>0)?$offInside:0;$days=$halfDay?0.5:$working+$sandwich;return ['requested_days'=>$halfDay?0.5:$working,'sandwich_days'=>$halfDay?0:$sandwich,'payable_days'=>$days,'policy'=>$policy];}
function oecrm_leave_balance($conn,$employeeId,$leaveTypeId,$year){$stmt=mysqli_prepare($conn,'SELECT *,(opening_balance+credited+adjusted-used-pending) available FROM employee_leave_balances WHERE employee_id=? AND leave_type_id=? AND balance_year=?');mysqli_stmt_bind_param($stmt,'iii',$employeeId,$leaveTypeId,$year);mysqli_stmt_execute($stmt);$r=mysqli_fetch_assoc(mysqli_stmt_get_result($stmt));mysqli_stmt_close($stmt);return $r;}
function oecrm_generate_comp_off_credits($conn,$companyId,$year,$month,$actor=0){$settings=mysqli_fetch_assoc(mysqli_query($conn,'SELECT * FROM leave_settings WHERE company_id='.(int)$companyId));if(!$settings)return 0;$start=sprintf('%04d-%02d-01',$year,$month);$end=date('Y-m-t',strtotime($start));$stmt=mysqli_prepare($conn,'SELECT s.* FROM attendance_sessions s JOIN employeestbl e ON e.id=s.employee_id WHERE e.company_id=? AND s.attendance_date BETWEEN ? AND ? AND s.actual_out IS NOT NULL AND s.effective_minutes>=?');mysqli_stmt_bind_param($stmt,'issi',$companyId,$start,$end,$settings['minimum_comp_off_minutes']);mysqli_stmt_execute($stmt);$rows=mysqli_stmt_get_result($stmt);$count=0;while($r=mysqli_fetch_assoc($rows)){$shift=oecrm_employee_shift($conn,$r['employee_id'],$r['attendance_date']);$weekly=$shift?oecrm_shift_is_weekly_off($conn,$shift['id'],$r['attendance_date']):false;$holiday=oecrm_is_holiday($conn,$r['attendance_date'],$companyId);if(!$weekly&&!$holiday)continue;$source=$holiday?'holiday_work':'weekly_off_work';$existsStmt=mysqli_prepare($conn,'SELECT id FROM comp_off_ledger WHERE employee_id=? AND source_type=? AND source_date=? AND status<>"cancelled"');mysqli_stmt_bind_param($existsStmt,'iss',$r['employee_id'],$source,$r['attendance_date']);mysqli_stmt_execute($existsStmt);$exists=mysqli_fetch_assoc(mysqli_stmt_get_result($existsStmt));mysqli_stmt_close($existsStmt);if($exists)continue;$credit=$r['effective_minutes']>=((int)$shift['required_minutes'])?1.0:0.5;$expiry=date('Y-m-d',strtotime($r['attendance_date'].' +'.(int)$settings['comp_off_expiry_days'].' days'));$notes=ucwords(str_replace('_',' ',$source)).' attendance credit';$ins=mysqli_prepare($conn,'INSERT INTO comp_off_ledger(employee_id,source_type,source_date,credit_days,expiry_date,reference_type,reference_id,notes,created_by) VALUES(?,?,?,?,?,"attendance_session",?,?,?)');mysqli_stmt_bind_param($ins,'issdsisi',$r['employee_id'],$source,$r['attendance_date'],$credit,$expiry,$r['id'],$notes,$actor);mysqli_stmt_execute($ins);mysqli_stmt_close($ins);$count++;}mysqli_stmt_close($stmt);return $count;}
