<?php
function oecrm_letter_types(){return ['offer'=>'Offer Letter','appointment'=>'Appointment Letter','internship'=>'Internship Letter','probation_extension'=>'Probation Extension Letter','confirmation'=>'Confirmation Letter','promotion'=>'Promotion Letter','transfer'=>'Transfer Letter','salary_revision'=>'Salary Revision Letter','increment'=>'Increment Letter','appreciation'=>'Appreciation Letter','warning'=>'Warning Letter','show_cause'=>'Show Cause Notice','performance_improvement'=>'Performance Improvement Plan','experience'=>'Experience Letter','relieving'=>'Relieving Letter','resignation_acceptance'=>'Resignation Acceptance Letter','termination'=>'Termination Letter','full_final_settlement'=>'Full & Final Settlement Letter'];}
function oecrm_letter_presets(){
$sign='<p>Sincerely,<br><strong>{{company_name}}</strong><br>Human Resources</p>';
return [
'offer'=>['subject'=>'Employment Offer - {{company_name}}','body'=>'<p>Dear {{employee_name}},</p><p>We are pleased to offer you employment with {{company_name}} as <strong>{{designation}}</strong>. Your proposed joining date is {{joining_date}}.</p><p>This offer is subject to company joining formalities and policies.</p>'.$sign],
'appointment'=>['subject'=>'Appointment as {{designation}}','body'=>'<p>Dear {{employee_name}},</p><p>You are appointed as <strong>{{designation}}</strong> with {{company_name}} effective {{joining_date}}. Your employment is governed by company policies and service conditions.</p>'.$sign],
'internship'=>['subject'=>'Internship Engagement Letter','body'=>'<p>Dear {{employee_name}},</p><p>We are pleased to engage you as an intern with {{company_name}} from {{joining_date}}. You will comply with company confidentiality and conduct requirements.</p>'.$sign],
'probation_extension'=>['subject'=>'Extension of Probation Period','body'=>'<p>Dear {{employee_name}},</p><p>Your probation period is extended until <strong>{{effective_date}}</strong> for additional performance assessment. Your progress will be reviewed during this period.</p>'.$sign],
'confirmation'=>['subject'=>'Confirmation of Employment','body'=>'<p>Dear {{employee_name}},</p><p>We are pleased to confirm your employment as <strong>{{designation}}</strong> effective {{effective_date}}. All other employment terms remain unchanged.</p>'.$sign],
'promotion'=>['subject'=>'Promotion to {{new_designation}}','body'=>'<p>Dear {{employee_name}},</p><p>In recognition of your contribution, you are promoted to <strong>{{new_designation}}</strong> effective {{effective_date}}.</p>'.$sign],
'transfer'=>['subject'=>'Employee Transfer Letter','body'=>'<p>Dear {{employee_name}},</p><p>You are transferred to the new role or location communicated by management effective {{effective_date}}. Reporting details will be shared separately.</p>'.$sign],
'salary_revision'=>['subject'=>'Salary Revision Effective {{effective_date}}','body'=>'<p>Dear {{employee_name}},</p><p>Your compensation has been revised to <strong>{{revised_salary}}</strong> effective {{effective_date}}. The revision will reflect in the applicable payroll cycle.</p>'.$sign],
'increment'=>['subject'=>'Annual Increment Letter','body'=>'<p>Dear {{employee_name}},</p><p>We are pleased to grant you an increment, revising your compensation to <strong>{{revised_salary}}</strong> effective {{effective_date}}.</p>'.$sign],
'appreciation'=>['subject'=>'Letter of Appreciation','body'=>'<p>Dear {{employee_name}},</p><p>We sincerely appreciate your contribution, commitment and professional conduct. Your efforts have positively supported the team and {{company_name}}.</p>'.$sign],
'warning'=>['subject'=>'Formal Warning Letter','body'=>'<p>Dear {{employee_name}},</p><p>This is a formal warning regarding <strong>{{reason}}</strong>. Immediate corrective action is expected. Repetition may result in further disciplinary action.</p>'.$sign],
'show_cause'=>['subject'=>'Show Cause Notice','body'=>'<p>Dear {{employee_name}},</p><p>You are required to provide a written explanation regarding <strong>{{reason}}</strong> within the timeline communicated by Human Resources.</p>'.$sign],
'performance_improvement'=>['subject'=>'Performance Improvement Plan','body'=>'<p>Dear {{employee_name}},</p><p>A performance improvement plan begins effective {{effective_date}}. Areas requiring improvement: {{reason}}. Your manager will review progress and provide guidance.</p>'.$sign],
'experience'=>['subject'=>'Experience Certificate - {{employee_name}}','body'=>'<p>To Whom It May Concern,</p><p>This certifies that <strong>{{employee_name}}</strong> ({{employee_code}}) worked with {{company_name}} as {{designation}} from {{joining_date}} to {{last_working_date}}.</p><p>We wish them success.</p>'.$sign],
'relieving'=>['subject'=>'Relieving Letter','body'=>'<p>Dear {{employee_name}},</p><p>You are relieved from your duties with {{company_name}} at the close of business on {{last_working_date}}, subject to completion of clearance formalities.</p>'.$sign],
'resignation_acceptance'=>['subject'=>'Acceptance of Resignation','body'=>'<p>Dear {{employee_name}},</p><p>Your resignation has been accepted. Your last working date is <strong>{{last_working_date}}</strong>. Please complete handover and clearance.</p>'.$sign],
'termination'=>['subject'=>'Termination of Employment','body'=>'<p>Dear {{employee_name}},</p><p>Your employment with {{company_name}} is terminated effective {{effective_date}} due to {{reason}}. Please complete company property return and clearance.</p>'.$sign],
'full_final_settlement'=>['subject'=>'Full and Final Settlement','body'=>'<p>Dear {{employee_name}},</p><p>This confirms processing of your full and final settlement following your last working date {{last_working_date}}, subject to final clearance and statutory deductions.</p>'.$sign],
];}
function oecrm_seed_letter_templates($conn,$companyId,$actor){$types=oecrm_letter_types();$presets=oecrm_letter_presets();$check=mysqli_prepare($conn,'SELECT id FROM hr_letter_templates WHERE company_id=? AND letter_type=? LIMIT 1');$insert=mysqli_prepare($conn,'INSERT INTO hr_letter_templates(company_id,letter_type,name,subject,body_html,is_default,status,created_by) VALUES(?,?,?,?,?,1,1,?)');foreach($types as $key=>$label){mysqli_stmt_bind_param($check,'is',$companyId,$key);mysqli_stmt_execute($check);if(mysqli_fetch_assoc(mysqli_stmt_get_result($check)))continue;$name='Standard '.$label;$subject=$presets[$key]['subject'];$body=$presets[$key]['body'];mysqli_stmt_bind_param($insert,'issssi',$companyId,$key,$name,$subject,$body,$actor);mysqli_stmt_execute($insert);}mysqli_stmt_close($check);mysqli_stmt_close($insert);}
function oecrm_letter_tokens($employee,$company,$extra=[]){$values=['{{employee_name}}'=>$employee['name']??'','{{employee_code}}'=>$employee['employeeCode']??'','{{designation}}'=>$employee['designation']??'','{{joining_date}}'=>!empty($employee['joiningDate'])?date('d M Y',strtotime($employee['joiningDate'])):'','{{employee_email}}'=>$employee['companyEmail']??'','{{employee_address}}'=>$employee['address']??'','{{company_name}}'=>$company['display_name']??'','{{company_legal_name}}'=>$company['legal_name']??'','{{company_address}}'=>$company['address']??'','{{company_email}}'=>$company['email']??'','{{company_phone}}'=>$company['phone']??'','{{issue_date}}'=>date('d M Y'),'{{current_date}}'=>date('d M Y')];foreach($extra as $key=>$value)$values['{{'.$key.'}}']=$value;return $values;}
function oecrm_render_letter($html,$employee,$company,$extra=[]){return strtr($html,oecrm_letter_tokens($employee,$company,$extra));}
function oecrm_letter_reference($conn,$companyId,$type){$prefix=strtoupper(substr(preg_replace('/[^a-z]/','',$type),0,3));$base=$prefix.'-'.date('Ym').'-';$stmt=mysqli_prepare($conn,'SELECT reference_no FROM hr_letters WHERE company_id=? AND reference_no LIKE CONCAT(?,"%") ORDER BY id DESC LIMIT 1');mysqli_stmt_bind_param($stmt,'is',$companyId,$base);mysqli_stmt_execute($stmt);$row=mysqli_fetch_assoc(mysqli_stmt_get_result($stmt));mysqli_stmt_close($stmt);$next=$row?((int)substr($row['reference_no'],-4)+1):1;return $base.str_pad($next,4,'0',STR_PAD_LEFT);}
function oecrm_letter_print_styles(){return '<style>*{box-sizing:border-box}body{margin:0;background:#eef1f6;color:#293044;font-family:Arial,sans-serif}.toolbar{max-width:900px;margin:18px auto;display:flex;gap:8px;justify-content:flex-end}.toolbar a,.toolbar button{border:0;background:#635bff;color:#fff;padding:10px 15px;border-radius:5px;text-decoration:none;cursor:pointer}.letter{width:210mm;min-height:297mm;margin:0 auto 24px;background:#fff;padding:22mm 20mm;box-shadow:0 8px 30px rgba(35,42,63,.12)}.letter-head{display:flex;justify-content:space-between;border-bottom:2px solid #635bff;padding-bottom:18px;margin-bottom:30px}.letter-head h1{font-size:21px;margin:0}.letter-meta{text-align:right;font-size:12px;color:#697089}.letter-body{font-size:14px;line-height:1.75}.letter-body h2{font-size:20px}.letter-footer{margin-top:55px;border-top:1px solid #ddd;padding-top:16px;font-size:12px;color:#697089}@media print{body{background:#fff}.toolbar{display:none}.letter{margin:0;box-shadow:none;width:auto;min-height:auto;padding:15mm}}</style>';}
