<?php
$active_menu='hr_letters';$active_submenu='letter_templates';include 'header.php';require_once __DIR__.'/../foundation.php';require_once __DIR__.'/../hr_letters.php';
oecrm_require_permission($conn,'hr_letter_templates','view');$companyId=oecrm_current_company_id($conn);
if(oecrm_can($conn,'hr_letter_templates','create'))oecrm_seed_letter_templates($conn,$companyId,(int)$_SESSION['adminId']);
$editId=(int)($_GET['edit']??0);$edit=null;if($editId){$stmt=mysqli_prepare($conn,'SELECT * FROM hr_letter_templates WHERE id=? AND company_id=?');mysqli_stmt_bind_param($stmt,'ii',$editId,$companyId);mysqli_stmt_execute($stmt);$edit=mysqli_fetch_assoc(mysqli_stmt_get_result($stmt));mysqli_stmt_close($stmt);}
$list=mysqli_query($conn,'SELECT * FROM hr_letter_templates WHERE company_id='.(int)$companyId.' ORDER BY status DESC,letter_type,name');$flash=$_SESSION['letter_flash']??'';unset($_SESSION['letter_flash']);$presets=oecrm_letter_presets();
?>
<div id="page-wrapper" class="compact-admin-page letter-admin-page"><?php if($flash):?><div class="alert alert-success"><?php echo oecrm_h($flash);?></div><?php endif;?>
<div class="letter-layout"><div class="panel panel-default"><div class="panel-heading"><?php echo $edit?'Edit':'New';?> Letter Template</div><div class="panel-body">
<form method="post" action="hrLetterAction.php" class="letter-form"><?php echo oecrm_csrf_field();?><input type="hidden" name="action" value="save_template"><input type="hidden" name="id" value="<?php echo (int)($edit['id']??0);?>">
<div class="letter-form-grid"><div class="form-group"><label>Letter Type</label><select id="templateLetterType" name="letter_type" class="form-control" required><?php foreach(oecrm_letter_types() as $key=>$label):?><option value="<?php echo $key;?>" <?php echo ($edit['letter_type']??'')===$key?'selected':'';?>><?php echo $label;?></option><?php endforeach;?></select></div><div class="form-group"><label>Template Name</label><input id="templateName" name="name" class="form-control" required value="<?php echo oecrm_h($edit['name']??'');?>"></div></div>
<div class="form-group"><label>Email / Letter Subject</label><input id="templateSubject" name="subject" class="form-control" required value="<?php echo oecrm_h($edit['subject']??'');?>"></div>
<div class="form-group"><label>Letter Content</label><textarea id="templateBody" name="body_html" class="form-control letter-editor" required><?php echo oecrm_h($edit['body_html']??'');?></textarea></div>
<div class="token-help"><strong>Auto-fill tokens</strong><span>{{employee_name}}</span><span>{{employee_code}}</span><span>{{designation}}</span><span>{{joining_date}}</span><span>{{company_name}}</span><span>{{effective_date}}</span><span>{{new_designation}}</span><span>{{revised_salary}}</span><span>{{last_working_date}}</span><span>{{reason}}</span></div>
<label class="check-line"><input type="checkbox" name="is_default" <?php echo !empty($edit['is_default'])?'checked':'';?>> Default template for this type</label><label class="check-line"><input type="checkbox" name="status" <?php echo !isset($edit['status'])||$edit['status']?'checked':'';?>> Active</label><button class="btn btn-primary"><i class="fa fa-save"></i> Save Template</button>
</form></div></div>
<div class="panel panel-default"><div class="panel-heading">Reusable Templates</div><div class="panel-body table-responsive"><table class="table foundation-table"><thead><tr><th>Type</th><th>Name</th><th>Default</th><th>Status</th><th>Action</th></tr></thead><tbody><?php while($row=mysqli_fetch_assoc($list)):?><tr><td><?php echo oecrm_h(oecrm_letter_types()[$row['letter_type']]??$row['letter_type']);?></td><td><strong><?php echo oecrm_h($row['name']);?></strong><small><?php echo oecrm_h($row['subject']);?></small></td><td><?php echo $row['is_default']?'Yes':'No';?></td><td><span class="letter-status <?php echo $row['status']?'issued':'cancelled';?>"><?php echo $row['status']?'Active':'Inactive';?></span></td><td><a class="icon-action" href="hrLetterTemplates.php?edit=<?php echo (int)$row['id'];?>" title="Edit"><i class="fa fa-pencil"></i></a></td></tr><?php endwhile;?></tbody></table></div></div>
</div></div></div>
<script>
(function(){var presets=<?php echo json_encode($presets,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);?>,types=<?php echo json_encode(oecrm_letter_types(),JSON_UNESCAPED_UNICODE);?>,select=document.getElementById('templateLetterType'),name=document.getElementById('templateName'),subject=document.getElementById('templateSubject'),body=document.getElementById('templateBody'),editing=<?php echo $edit?'true':'false';?>;function fill(){var preset=presets[select.value];if(!preset)return;if(!editing||!name.value)name.value='Standard '+types[select.value];if(!editing||!subject.value)subject.value=preset.subject;if(!editing||!body.value)body.value=preset.body;editing=false;}select.addEventListener('change',fill);fill();}());
</script>
<?php include 'footer.php';?>
