ALTER TABLE companies
    ADD COLUMN IF NOT EXISTS country_id MEDIUMINT UNSIGNED NULL AFTER country_code,
    ADD COLUMN IF NOT EXISTS state_id MEDIUMINT UNSIGNED NULL AFTER country_id,
    ADD COLUMN IF NOT EXISTS city_id MEDIUMINT UNSIGNED NULL AFTER state_id;
