CREATE TABLE IF NOT EXISTS digital_subscriptions (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,company_id INT NOT NULL,asset_type ENUM('domain','hosting','ssl','software','ai_tool','cloud','other') NOT NULL,name VARCHAR(180) NOT NULL,provider VARCHAR(150) DEFAULT NULL,login_url VARCHAR(500) DEFAULT NULL,username VARCHAR(180) DEFAULT NULL,secret_encrypted TEXT DEFAULT NULL,recovery_email VARCHAR(180) DEFAULT NULL,start_date DATE DEFAULT NULL,renewal_date DATE DEFAULT NULL,billing_cycle ENUM('monthly','quarterly','half_yearly','yearly','other') NOT NULL DEFAULT 'yearly',cost DECIMAL(14,2) NOT NULL DEFAULT 0,currency_code CHAR(3) NOT NULL DEFAULT 'INR',status ENUM('active','expired','cancelled') NOT NULL DEFAULT 'active',notes TEXT DEFAULT NULL,created_by INT NOT NULL DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_subscription_renewal(company_id,renewal_date,status)
);
CREATE TABLE IF NOT EXISTS finance_invoices (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,company_id INT NOT NULL,client_id BIGINT NOT NULL,project_id INT DEFAULT NULL,invoice_number VARCHAR(60) NOT NULL,invoice_type ENUM('gst','non_gst','international') NOT NULL DEFAULT 'gst',invoice_date DATE NOT NULL,due_date DATE NOT NULL,currency_code CHAR(3) NOT NULL DEFAULT 'INR',subtotal DECIMAL(14,2) NOT NULL DEFAULT 0,tax_amount DECIMAL(14,2) NOT NULL DEFAULT 0,total_amount DECIMAL(14,2) NOT NULL DEFAULT 0,paid_amount DECIMAL(14,2) NOT NULL DEFAULT 0,status ENUM('draft','sent','viewed','partially_paid','paid','overdue','cancelled') NOT NULL DEFAULT 'draft',notes TEXT DEFAULT NULL,created_by INT NOT NULL DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_invoice(company_id,invoice_number),KEY idx_invoice_status(company_id,status,due_date)
);
CREATE TABLE IF NOT EXISTS finance_invoice_items (id BIGINT AUTO_INCREMENT PRIMARY KEY,invoice_id BIGINT NOT NULL,description VARCHAR(255) NOT NULL,quantity DECIMAL(10,2) NOT NULL DEFAULT 1,rate DECIMAL(14,2) NOT NULL DEFAULT 0,tax_percent DECIMAL(5,2) NOT NULL DEFAULT 0,amount DECIMAL(14,2) NOT NULL DEFAULT 0,KEY idx_invoice_item(invoice_id));
CREATE TABLE IF NOT EXISTS finance_payments (id BIGINT AUTO_INCREMENT PRIMARY KEY,company_id INT NOT NULL,invoice_id BIGINT NOT NULL,payment_date DATE NOT NULL,amount DECIMAL(14,2) NOT NULL,transaction_reference VARCHAR(150) DEFAULT NULL,gateway ENUM('bank','paypal','stripe','wise','cash','other') NOT NULL DEFAULT 'bank',gateway_fee DECIMAL(14,2) NOT NULL DEFAULT 0,bank_charge DECIMAL(14,2) NOT NULL DEFAULT 0,created_by INT NOT NULL DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,KEY idx_payment_invoice(invoice_id));
CREATE TABLE IF NOT EXISTS finance_expenses (id BIGINT AUTO_INCREMENT PRIMARY KEY,company_id INT NOT NULL,category VARCHAR(100) NOT NULL,expense_date DATE NOT NULL,vendor VARCHAR(180) DEFAULT NULL,description VARCHAR(255) NOT NULL,amount DECIMAL(14,2) NOT NULL,tax_amount DECIMAL(14,2) NOT NULL DEFAULT 0,currency_code CHAR(3) NOT NULL DEFAULT 'INR',bank_account_id INT DEFAULT NULL,attachment VARCHAR(255) DEFAULT NULL,created_by INT NOT NULL DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,KEY idx_fin_expense(company_id,expense_date,category));
CREATE TABLE IF NOT EXISTS employee_exits (id BIGINT AUTO_INCREMENT PRIMARY KEY,company_id INT NOT NULL,employee_id INT NOT NULL,resignation_date DATE DEFAULT NULL,last_working_date DATE NOT NULL,exit_type ENUM('resignation','termination','retirement','other') NOT NULL DEFAULT 'resignation',status ENUM('initiated','clearance','settlement','completed','cancelled') NOT NULL DEFAULT 'initiated',pending_salary DECIMAL(14,2) NOT NULL DEFAULT 0,retention_release DECIMAL(14,2) NOT NULL DEFAULT 0,deductions DECIMAL(14,2) NOT NULL DEFAULT 0,final_settlement DECIMAL(14,2) NOT NULL DEFAULT 0,notes TEXT DEFAULT NULL,created_by INT NOT NULL DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_exit(company_id,status));
CREATE TABLE IF NOT EXISTS exit_checklist (id BIGINT AUTO_INCREMENT PRIMARY KEY,exit_id BIGINT NOT NULL,item_type ENUM('asset','access','project','document','other') NOT NULL,item_label VARCHAR(180) NOT NULL,status ENUM('pending','cleared','not_applicable') NOT NULL DEFAULT 'pending',cleared_by INT DEFAULT NULL,cleared_at DATETIME DEFAULT NULL,notes VARCHAR(500) DEFAULT NULL,KEY idx_exit_item(exit_id,status));
INSERT IGNORE INTO permissions(module_key,action_key,label) VALUES
('subscriptions','view','View subscriptions'),('subscriptions','create','Create subscriptions'),('subscriptions','edit','Edit subscriptions'),('subscriptions','reveal','Reveal encrypted credentials'),
('finance','view','View finance'),('finance','create','Create finance records'),('finance','edit','Edit finance records'),('finance','reports','View financial reports'),
('gst','view','View GST reports'),('dashboards','view','View analytics dashboards'),
('employee_exit','view','View employee exits'),('employee_exit','create','Initiate employee exit'),('employee_exit','edit','Manage exit clearance'),('employee_exit','settle','Complete final settlement');
