<?php
$active_menu='employee';
include 'header.php';
require_once __DIR__.'/../foundation.php';
oecrm_require_permission($conn,'employee_profiles','view');
$employeeId=oecrm_int_param($_GET,'id');
$stmt=mysqli_prepare($conn,'SELECT e.*,p.*,c.display_name company_name,d.name department_name FROM employeestbl e LEFT JOIN employee_profiles p ON p.employee_id=e.id LEFT JOIN companies c ON c.id=e.company_id LEFT JOIN departments d ON d.id=e.department_id WHERE e.id=?');
mysqli_stmt_bind_param($stmt,'i',$employeeId);mysqli_stmt_execute($stmt);$employee=mysqli_fetch_assoc(mysqli_stmt_get_result($stmt));mysqli_stmt_close($stmt);
if(!$employee){http_response_code(404);exit('Employee not found.');}
$message=$_SESSION['employee_flash']??'';unset($_SESSION['employee_flash']);
$contracts=mysqli_query($conn,'SELECT * FROM employee_contracts WHERE employee_id='.(int)$employeeId.' ORDER BY id DESC');
$increments=mysqli_query($conn,'SELECT * FROM employee_increments WHERE employee_id='.(int)$employeeId.' ORDER BY effective_date DESC,id DESC');
$documents=mysqli_query($conn,'SELECT * FROM employee_documents WHERE employee_id='.(int)$employeeId.' ORDER BY id DESC');
?>
<div id="page-wrapper" class="compact-admin-page employee-profile-page">
<?php if($message):?><div class="alert alert-success"><?php echo oecrm_h($message);?></div><?php endif;?>
<div class="employee-profile-hero"><div class="employee-avatar"><?php echo oecrm_h(strtoupper(substr($employee['name'],0,1)));?></div><div class="employee-identity"><h2><?php echo oecrm_h($employee['name']);?></h2><p><?php echo oecrm_h($employee['employeeCode'].' · '.$employee['designation']);?></p><div><span><?php echo oecrm_h($employee['company_name']?:'Unassigned company');?></span><span><?php echo oecrm_h($employee['department_name']?:'No department');?></span><span class="status-pill <?php echo ($employee['employment_status']??'active')==='active'?'active':'inactive';?>"><?php echo oecrm_h(ucwords(str_replace('_',' ',$employee['employment_status']??'active')));?></span></div></div><div class="employee-hero-actions"><a class="btn btn-default" href="editEmployee.php?edit=<?php echo $employeeId;?>"><i class="fa fa-pencil"></i> Edit Basic Details</a><a class="btn btn-default" href="manageEmployee.php"><i class="fa fa-arrow-left"></i> Employees</a></div></div>
<div class="employee-profile-layout"><main>
<div class="panel panel-default"><div class="panel-heading">Employment Details</div><div class="panel-body"><form method="post" action="employeeProfileAction.php" class="employee-detail-form"><?php echo oecrm_csrf_field();?><input type="hidden" name="action" value="profile"><input type="hidden" name="employee_id" value="<?php echo $employeeId;?>">
<div class="employee-form-grid"><div class="form-group"><label>Employment Type</label><select class="form-control" name="employment_type"><?php foreach(['permanent','probation','contract','intern','consultant'] as $v):?><option <?php echo ($employee['employment_type']??'permanent')===$v?'selected':'';?> value="<?php echo $v;?>"><?php echo ucwords($v);?></option><?php endforeach;?></select></div><div class="form-group"><label>Employment Status</label><select class="form-control" name="employment_status"><?php foreach(['active','inactive','notice_period','resigned','terminated','retired'] as $v):?><option <?php echo ($employee['employment_status']??'active')===$v?'selected':'';?> value="<?php echo $v;?>"><?php echo ucwords(str_replace('_',' ',$v));?></option><?php endforeach;?></select></div><div class="form-group"><label>Confirmation Date</label><input type="date" class="form-control" name="confirmation_date" value="<?php echo oecrm_h($employee['confirmation_date']);?>"></div><div class="form-group"><label>Notice Period Days</label><input type="number" min="0" class="form-control" name="notice_period_days" value="<?php echo (int)$employee['notice_period_days'];?>"></div><div class="form-group"><label>Exit Date</label><input type="date" class="form-control" name="exit_date" value="<?php echo oecrm_h($employee['exit_date']);?>"></div><div class="form-group"><label>Exit Reason</label><input class="form-control" name="exit_reason" value="<?php echo oecrm_h($employee['exit_reason']);?>"></div><div class="form-group"><label>Emergency Contact Name</label><input class="form-control" name="emergency_contact_name" value="<?php echo oecrm_h($employee['emergency_contact_name']);?>"></div><div class="form-group"><label>Emergency Contact Phone</label><input class="form-control" name="emergency_contact_phone" value="<?php echo oecrm_h($employee['emergency_contact_phone']);?>"></div><div class="form-group"><label>Blood Group</label><input class="form-control" name="blood_group" value="<?php echo oecrm_h($employee['blood_group']);?>"></div><div class="form-group"><label>Marital Status</label><select class="form-control" name="marital_status"><option value="">Select</option><?php foreach(['single','married','divorced','widowed'] as $v):?><option <?php echo ($employee['marital_status']??'')===$v?'selected':'';?>><?php echo ucwords($v);?></option><?php endforeach;?></select></div><div class="form-group span-2"><label>Current Address</label><textarea class="form-control" name="current_address"><?php echo oecrm_h($employee['current_address']);?></textarea></div><div class="form-group span-2"><label>Permanent Address</label><textarea class="form-control" name="permanent_address"><?php echo oecrm_h($employee['permanent_address']);?></textarea></div></div><div class="profile-form-actions"><button class="btn btn-primary"><i class="fa fa-save"></i> Save Employment Details</button></div></form></div></div>
<div class="panel panel-default"><div class="panel-heading">Contracts</div><div class="panel-body"><form method="post" action="employeeProfileAction.php" class="inline-record-form"><?php echo oecrm_csrf_field();?><input type="hidden" name="action" value="contract"><input type="hidden" name="employee_id" value="<?php echo $employeeId;?>"><select class="form-control" name="contract_type"><?php foreach(['employment','nda','consulting','internship','other'] as $v):?><option value="<?php echo $v;?>"><?php echo ucwords($v);?></option><?php endforeach;?></select><input class="form-control" name="title" placeholder="Contract title" required><input type="date" class="form-control" name="start_date"><input type="date" class="form-control" name="end_date"><button class="btn btn-primary"><i class="fa fa-plus"></i> Add</button></form><div class="table-responsive"><table class="table profile-table"><thead><tr><th>Title</th><th>Type</th><th>Period</th><th>Status</th></tr></thead><tbody><?php if(mysqli_num_rows($contracts)===0):?><tr><td colspan="4" class="empty-cell">No contracts added.</td></tr><?php endif;?><?php while($r=mysqli_fetch_assoc($contracts)):?><tr><td><?php echo oecrm_h($r['title']);?></td><td><?php echo oecrm_h(ucwords($r['contract_type']));?></td><td><?php echo oecrm_h(($r['start_date']?:'—').' to '.($r['end_date']?:'Open'));?></td><td><span class="status-pill active"><?php echo oecrm_h(ucwords($r['status']));?></span></td></tr><?php endwhile;?></tbody></table></div></div></div>
<div class="panel panel-default"><div class="panel-heading">Increment History</div><div class="panel-body"><form method="post" action="employeeProfileAction.php" class="inline-record-form increment-form"><?php echo oecrm_csrf_field();?><input type="hidden" name="action" value="increment"><input type="hidden" name="employee_id" value="<?php echo $employeeId;?>"><input type="date" class="form-control" name="effective_date" required><input type="number" step="0.01" class="form-control" name="revised_salary" placeholder="Revised salary" required><input class="form-control" name="reason" placeholder="Reason"><button class="btn btn-primary"><i class="fa fa-plus"></i> Add</button></form><div class="table-responsive"><table class="table profile-table"><thead><tr><th>Effective Date</th><th>Previous</th><th>Revised</th><th>Increase</th><th>Reason</th></tr></thead><tbody><?php if(mysqli_num_rows($increments)===0):?><tr><td colspan="5" class="empty-cell">No increments recorded.</td></tr><?php endif;?><?php while($r=mysqli_fetch_assoc($increments)):?><tr><td><?php echo oecrm_h($r['effective_date']);?></td><td>?<?php echo number_format($r['previous_salary'],2);?></td><td>?<?php echo number_format($r['revised_salary'],2);?></td><td><?php echo number_format($r['increment_percent'],2);?>%</td><td><?php echo oecrm_h($r['reason']);?></td></tr><?php endwhile;?></tbody></table></div></div></div>
</main><aside><div class="panel panel-default"><div class="panel-heading">Documents</div><div class="panel-body"><form method="post" action="employeeProfileAction.php" enctype="multipart/form-data" class="document-upload-form"><?php echo oecrm_csrf_field();?><input type="hidden" name="action" value="document"><input type="hidden" name="employee_id" value="<?php echo $employeeId;?>"><div class="form-group"><label>Document Type</label><select class="form-control" name="document_type"><?php foreach(['resume','aadhaar','pan','passport','driving_licence','address_proof','photograph','experience_letter','relieving_letter','salary_slip','contract','other'] as $v):?><option value="<?php echo $v;?>"><?php echo ucwords(str_replace('_',' ',$v));?></option><?php endforeach;?></select></div><div class="form-group"><label>Title</label><input class="form-control" name="title" required></div><div class="form-group"><label>File</label><input type="file" class="form-control" name="document" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" required></div><button class="btn btn-primary btn-block"><i class="fa fa-upload"></i> Upload Document</button></form><div class="document-list"><?php if(mysqli_num_rows($documents)===0):?><div class="empty-cell">No documents uploaded.</div><?php endif;?><?php while($r=mysqli_fetch_assoc($documents)):?><div class="document-item"><i class="fa fa-file-text-o"></i><div><strong><?php echo oecrm_h($r['title']);?></strong><small><?php echo oecrm_h(ucwords(str_replace('_',' ',$r['document_type'])));?></small></div><a href="employeeDocument.php?id=<?php echo (int)$r['id'];?>" title="Download"><i class="fa fa-download"></i></a></div><?php endwhile;?></div></div></div>
<div class="panel panel-default"><div class="panel-heading">Contact Summary</div><div class="panel-body profile-summary"><p><i class="fa fa-envelope"></i><span><?php echo oecrm_h($employee['companyEmail']);?></span></p><p><i class="fa fa-phone"></i><span><?php echo oecrm_h($employee['mobile1']);?></span></p><p><i class="fa fa-calendar"></i><span>Joined <?php echo oecrm_h($employee['joiningDate']?:'Not set');?></span></p><p><i class="fa fa-money"></i><span>?<?php echo number_format((float)$employee['salary'],2);?></span></p></div></div></aside></div></div>
<?php include 'footer.php';?>