<?php
require_once __DIR__.'/dbconnect.php';
require_once __DIR__.'/../security.php';
require_once __DIR__.'/../foundation.php';
oecrm_require_admin_login();
if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);exit('Method not allowed.');}
oecrm_require_csrf();
$employeeId=oecrm_int_param($_POST,'employee_id');
$action=$_POST['action']??'';
$stmt=mysqli_prepare($conn,'SELECT id,salary FROM employeestbl WHERE id=?');mysqli_stmt_bind_param($stmt,'i',$employeeId);mysqli_stmt_execute($stmt);$employee=mysqli_fetch_assoc(mysqli_stmt_get_result($stmt));mysqli_stmt_close($stmt);if(!$employee){http_response_code(404);exit('Employee not found.');}

if($action==='profile'){
 oecrm_require_permission($conn,'employee_profiles','edit');
 $allowedTypes=['permanent','probation','contract','intern','consultant'];$allowedStatuses=['active','inactive','notice_period','resigned','terminated','retired'];
 $type=$_POST['employment_type']??'permanent';$status=$_POST['employment_status']??'active';if(!in_array($type,$allowedTypes,true)||!in_array($status,$allowedStatuses,true)){http_response_code(400);exit('Invalid employment value.');}
 $fields=['confirmation_date','exit_date'];foreach($fields as $f){if(($_POST[$f]??'')==='')$_POST[$f]=null;}
 $notice=max(0,(int)($_POST['notice_period_days']??0));$exitReason=trim($_POST['exit_reason']??'');$emergencyName=trim($_POST['emergency_contact_name']??'');$emergencyPhone=trim($_POST['emergency_contact_phone']??'');$blood=trim($_POST['blood_group']??'');$marital=trim($_POST['marital_status']??'');$current=trim($_POST['current_address']??'');$permanent=trim($_POST['permanent_address']??'');$confirmation=$_POST['confirmation_date'];$exitDate=$_POST['exit_date'];
 $old=mysqli_fetch_assoc(mysqli_query($conn,'SELECT * FROM employee_profiles WHERE employee_id='.(int)$employeeId));
 $stmt=mysqli_prepare($conn,'INSERT INTO employee_profiles(employee_id,employment_type,employment_status,confirmation_date,notice_period_days,exit_date,exit_reason,emergency_contact_name,emergency_contact_phone,blood_group,marital_status,current_address,permanent_address) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE employment_type=VALUES(employment_type),employment_status=VALUES(employment_status),confirmation_date=VALUES(confirmation_date),notice_period_days=VALUES(notice_period_days),exit_date=VALUES(exit_date),exit_reason=VALUES(exit_reason),emergency_contact_name=VALUES(emergency_contact_name),emergency_contact_phone=VALUES(emergency_contact_phone),blood_group=VALUES(blood_group),marital_status=VALUES(marital_status),current_address=VALUES(current_address),permanent_address=VALUES(permanent_address)');
 mysqli_stmt_bind_param($stmt,'isssissssssss',$employeeId,$type,$status,$confirmation,$notice,$exitDate,$exitReason,$emergencyName,$emergencyPhone,$blood,$marital,$current,$permanent);mysqli_stmt_execute($stmt);mysqli_stmt_close($stmt);
 if(($old['employment_status']??'')!==$status){$oldStatus=$old['employment_status']??null;$today=date('Y-m-d');$actor=(int)($_SESSION['adminId']??0);$stmt=mysqli_prepare($conn,'INSERT INTO employee_status_history(employee_id,old_status,new_status,effective_date,reason,changed_by) VALUES(?,?,?,?,?,?)');mysqli_stmt_bind_param($stmt,'issssi',$employeeId,$oldStatus,$status,$today,$exitReason,$actor);mysqli_stmt_execute($stmt);mysqli_stmt_close($stmt);mysqli_query($conn,'UPDATE employeestbl SET status='.(in_array($status,['active','notice_period'],true)?0:1).' WHERE id='.(int)$employeeId);}
 oecrm_audit($conn,'employee_profiles','update','employee',$employeeId,'Employment profile updated',$old,$_POST);$_SESSION['employee_flash']='Employment details updated.';
}elseif($action==='contract'){
 oecrm_require_permission($conn,'employee_contracts','create');$type=$_POST['contract_type']??'employment';$title=trim($_POST['title']??'');$start=$_POST['start_date']?:null;$end=$_POST['end_date']?:null;$actor=(int)($_SESSION['adminId']??0);if($title===''){http_response_code(400);exit('Contract title is required.');}$stmt=mysqli_prepare($conn,'INSERT INTO employee_contracts(employee_id,contract_type,title,start_date,end_date,created_by) VALUES(?,?,?,?,?,?)');mysqli_stmt_bind_param($stmt,'issssi',$employeeId,$type,$title,$start,$end,$actor);mysqli_stmt_execute($stmt);$id=mysqli_insert_id($conn);mysqli_stmt_close($stmt);oecrm_audit($conn,'employee_contracts','create','employee_contract',$id,'Employee contract added',null,$_POST);$_SESSION['employee_flash']='Contract added.';
}elseif($action==='increment'){
 oecrm_require_permission($conn,'employee_increments','create');$date=$_POST['effective_date']??'';$revised=(float)($_POST['revised_salary']??0);$previous=(float)$employee['salary'];$reason=trim($_POST['reason']??'');if(!$date||$revised<=0){http_response_code(400);exit('Effective date and revised salary are required.');}$amount=$revised-$previous;$percent=$previous>0?($amount/$previous)*100:0;$actor=(int)($_SESSION['adminId']??0);mysqli_begin_transaction($conn);$stmt=mysqli_prepare($conn,'INSERT INTO employee_increments(employee_id,effective_date,previous_salary,revised_salary,increment_amount,increment_percent,reason,approved_by,created_by) VALUES(?,?,?,?,?,?,?,?,?)');mysqli_stmt_bind_param($stmt,'isddddsii',$employeeId,$date,$previous,$revised,$amount,$percent,$reason,$actor,$actor);mysqli_stmt_execute($stmt);$id=mysqli_insert_id($conn);mysqli_stmt_close($stmt);$stmt=mysqli_prepare($conn,'UPDATE employeestbl SET salary=? WHERE id=?');$salaryString=(string)$revised;mysqli_stmt_bind_param($stmt,'si',$salaryString,$employeeId);mysqli_stmt_execute($stmt);mysqli_stmt_close($stmt);mysqli_commit($conn);oecrm_audit($conn,'employee_increments','create','employee_increment',$id,'Salary increment recorded',['salary'=>$previous],['salary'=>$revised,'effective_date'=>$date]);$_SESSION['employee_flash']='Increment recorded and current salary updated.';
}elseif($action==='document'){
 oecrm_require_permission($conn,'employee_documents','upload');$type=$_POST['document_type']??'other';$title=trim($_POST['title']??'');if($title===''){http_response_code(400);exit('Document title is required.');}$stored=oecrm_safe_upload($_FILES['document']??null,__DIR__.'/../storage/employee_documents',['pdf','jpg','jpeg','png','doc','docx']);$original=$_FILES['document']['name']??'';$mime=$_FILES['document']['type']??'';$size=(int)($_FILES['document']['size']??0);$actor=(int)($_SESSION['adminId']??0);$stmt=mysqli_prepare($conn,'INSERT INTO employee_documents(employee_id,document_type,title,stored_name,original_name,mime_type,file_size,uploaded_by) VALUES(?,?,?,?,?,?,?,?)');mysqli_stmt_bind_param($stmt,'isssssii',$employeeId,$type,$title,$stored,$original,$mime,$size,$actor);mysqli_stmt_execute($stmt);$id=mysqli_insert_id($conn);mysqli_stmt_close($stmt);oecrm_audit($conn,'employee_documents','upload','employee_document',$id,'Employee document uploaded',null,['employee_id'=>$employeeId,'type'=>$type,'title'=>$title]);$_SESSION['employee_flash']='Document uploaded securely.';
}else{http_response_code(400);exit('Invalid action.');}
header('Location: employeeProfile.php?id='.$employeeId);exit;