<?php
$active_menu='resources';include 'header.php';require_once __DIR__.'/../foundation.php';$id=(int)($_GET['id']??0);oecrm_require_permission($conn,'resources',$id?'edit':'create');$companyId=oecrm_current_company_id($conn);
$row=['id'=>0,'employee_id'=>'','client_id'=>'','project_id'=>'','allocation_type'=>'full_time','allocation_percent'=>'100','billing_rate'=>'0','billing_cycle'=>'monthly','salary_cost'=>'0','currency_code'=>'INR','start_date'=>date('Y-m-d'),'end_date'=>'','status'=>'active','notes'=>''];
if($id){$s=mysqli_prepare($conn,'SELECT * FROM resource_allocations WHERE id=? AND company_id=?');mysqli_stmt_bind_param($s,'ii',$id,$companyId);mysqli_stmt_execute($s);$found=mysqli_fetch_assoc(mysqli_stmt_get_result($s));mysqli_stmt_close($s);if(!$found){http_response_code(404);exit('Allocation not found.');}$row=$found;}
$employees=mysqli_query($conn,'SELECT DISTINCT e.id,e.employeeCode,e.name,e.company_id,c.display_name company_name,COALESCE((SELECT gross_salary FROM salary_structures s WHERE s.employee_id=e.id AND s.status=1 ORDER BY effective_from DESC LIMIT 1),CAST(e.salary AS DECIMAL(14,2))) salary_cost FROM employeestbl e LEFT JOIN companies c ON c.id=e.company_id LEFT JOIN project_team_members ptm ON ptm.employee_id=e.id AND (ptm.left_at IS NULL OR ptm.left_at>=CURDATE()) LEFT JOIN projectstbl tp ON tp.id=ptm.project_id AND tp.company_id='.(int)$companyId.' WHERE e.status=0 AND (e.company_id='.(int)$companyId.' OR tp.id IS NOT NULL) ORDER BY e.name');
$clients=mysqli_query($conn,'SELECT id,display_name FROM clients WHERE company_id='.(int)$companyId.' AND status IN ("active","prospect") ORDER BY display_name');
$projects=mysqli_query($conn,'SELECT id,projectName,client_id FROM projectstbl WHERE company_id='.(int)$companyId.' ORDER BY projectName');$error=$_SESSION['resource_error']??'';unset($_SESSION['resource_error']);
?>
<div id="page-wrapper" class="compact-admin-page resource-form-page"><div class="foundation-titlebar"><a href="resources.php"><i class="fa fa-arrow-left"></i> Resources</a><h2><?php echo $id?'Edit':'New';?> Resource Allocation</h2></div><?php if($error):?><div class="alert alert-danger"><?php echo oecrm_h($error);?></div><?php endif;?>
<div class="panel panel-default"><div class="panel-heading">Allocation Details</div><div class="panel-body"><form method="post" action="resourceAction.php" class="resource-form"><?php echo oecrm_csrf_field();?><input type="hidden" name="id" value="<?php echo (int)$row['id'];?>">
<div class="form-group"><label>Employee</label><select class="form-control" name="employee_id" id="resource_employee" required><option value="">Select employee</option><?php while($e=mysqli_fetch_assoc($employees)):?><option value="<?php echo (int)$e['id'];?>" data-cost="<?php echo oecrm_h($e['salary_cost']);?>" <?php echo $row['employee_id']==$e['id']?'selected':'';?>><?php echo oecrm_h($e['employeeCode'].' - '.$e['name'].' ('.$e['company_name'].')');?></option><?php endwhile;?></select><small class="help-block">Active company employees and shared project team members are available.</small></div>
<div class="form-group"><label>Client</label><select class="form-control" name="client_id" required><option value="">Select client</option><?php while($c=mysqli_fetch_assoc($clients)):?><option value="<?php echo (int)$c['id'];?>" <?php echo $row['client_id']==$c['id']?'selected':'';?>><?php echo oecrm_h($c['display_name']);?></option><?php endwhile;?></select></div>
<div class="form-group"><label>Project</label><select class="form-control" name="project_id"><option value="">General / No project</option><?php while($p=mysqli_fetch_assoc($projects)):?><option value="<?php echo (int)$p['id'];?>" <?php echo $row['project_id']==$p['id']?'selected':'';?>><?php echo oecrm_h($p['projectName']);?></option><?php endwhile;?></select></div>
<div class="form-group"><label>Allocation Type</label><select class="form-control" name="allocation_type"><?php foreach(['full_time'=>'Full Time Dedicated','part_time'=>'Part Time Dedicated','shared'=>'Shared Resource','hourly'=>'Hourly Resource'] as $v=>$label):?><option value="<?php echo $v;?>" <?php echo $row['allocation_type']===$v?'selected':'';?>><?php echo $label;?></option><?php endforeach;?></select></div>
<div class="form-group"><label>Allocation %</label><input class="form-control" type="number" min="1" max="100" step=".01" name="allocation_percent" value="<?php echo oecrm_h($row['allocation_percent']);?>" required></div>
<div class="form-group"><label>Billing Rate</label><input class="form-control" type="number" min="0" step=".01" name="billing_rate" value="<?php echo oecrm_h($row['billing_rate']);?>" required></div>
<div class="form-group"><label>Billing Cycle</label><select class="form-control" name="billing_cycle"><?php foreach(['monthly','hourly','fixed'] as $v):?><option value="<?php echo $v;?>" <?php echo $row['billing_cycle']===$v?'selected':'';?>><?php echo ucfirst($v);?></option><?php endforeach;?></select></div>
<div class="form-group"><label>Allocated Salary Cost</label><input class="form-control" id="resource_cost" type="number" min="0" step=".01" name="salary_cost" value="<?php echo oecrm_h($row['salary_cost']);?>" required></div>
<div class="form-group"><label>Currency</label><input class="form-control" maxlength="3" name="currency_code" value="<?php echo oecrm_h($row['currency_code']);?>"></div>
<div class="form-group"><label>Start Date</label><input class="form-control" type="date" name="start_date" value="<?php echo oecrm_h($row['start_date']);?>" required></div>
<div class="form-group"><label>End Date</label><input class="form-control" type="date" name="end_date" value="<?php echo oecrm_h($row['end_date']);?>"></div>
<div class="form-group"><label>Status</label><select class="form-control" name="status"><?php foreach(['planned','active','completed','cancelled'] as $v):?><option value="<?php echo $v;?>" <?php echo $row['status']===$v?'selected':'';?>><?php echo ucfirst($v);?></option><?php endforeach;?></select></div>
<div class="form-group resource-notes"><label>Notes</label><textarea class="form-control" name="notes" rows="3"><?php echo oecrm_h($row['notes']);?></textarea></div><div class="resource-actions"><button class="btn btn-primary"><i class="fa fa-save"></i> Save Allocation</button><a class="btn btn-default" href="resources.php">Cancel</a></div></form></div></div></div>
<script>document.getElementById('resource_employee').addEventListener('change',function(){var o=this.options[this.selectedIndex],c=document.getElementById('resource_cost');if(o.dataset.cost&&parseFloat(c.value||0)===0)c.value=o.dataset.cost;});</script><?php include 'footer.php';?>
