<?php
require_once __DIR__.'/dbconnect.php';require_once __DIR__.'/../security.php';require_once __DIR__.'/../foundation.php';oecrm_require_admin_login();if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);exit('Method not allowed.');}oecrm_require_csrf();$action=$_POST['action']??'';
if($action==='save'){
 $id=(int)($_POST['id']??0);oecrm_require_permission($conn,'shifts',$id?'edit':'create');$companyId=(int)($_POST['company_id']??0);$name=trim($_POST['name']??'');$code=strtoupper(trim($_POST['code']??''));$type=$_POST['shift_type']??'general';$start=$_POST['start_time']??'';$end=$_POST['end_time']??'';$required=max(1,(int)($_POST['required_minutes']??510));$break=max(0,(int)($_POST['break_minutes']??0));$graceIn=max(0,(int)($_POST['grace_in_minutes']??0));$graceOut=max(0,(int)($_POST['grace_out_minutes']??0));$status=isset($_POST['status'])?1:0;$crosses=strtotime($end)<=strtotime($start)?1:0;if(!$companyId||$name===''||$code===''||!preg_match('/^\d{2}:\d{2}$/',$start)||!preg_match('/^\d{2}:\d{2}$/',$end)){http_response_code(400);exit('Please complete all required shift fields.');}
 mysqli_begin_transaction($conn);try{if($id){$stmt=mysqli_prepare($conn,'UPDATE shifts SET company_id=?,name=?,code=?,shift_type=?,start_time=?,end_time=?,crosses_midnight=?,required_minutes=?,break_minutes=?,grace_in_minutes=?,grace_out_minutes=?,status=? WHERE id=?');mysqli_stmt_bind_param($stmt,'isssssiiiiiii',$companyId,$name,$code,$type,$start,$end,$crosses,$required,$break,$graceIn,$graceOut,$status,$id);}else{$stmt=mysqli_prepare($conn,'INSERT INTO shifts(company_id,name,code,shift_type,start_time,end_time,crosses_midnight,required_minutes,break_minutes,grace_in_minutes,grace_out_minutes,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');mysqli_stmt_bind_param($stmt,'isssssiiiiii',$companyId,$name,$code,$type,$start,$end,$crosses,$required,$break,$graceIn,$graceOut,$status);}mysqli_stmt_execute($stmt);if(!$id)$id=mysqli_insert_id($conn);mysqli_stmt_close($stmt);$stmt=mysqli_prepare($conn,'DELETE FROM shift_weekly_off_rules WHERE shift_id=?');mysqli_stmt_bind_param($stmt,'i',$id);mysqli_stmt_execute($stmt);mysqli_stmt_close($stmt);$insert=mysqli_prepare($conn,'INSERT INTO shift_weekly_off_rules(shift_id,weekday,week_of_month,is_off) VALUES(?,?,?,1)');foreach(($_POST['weekly_off']??[]) as $rule){if(!preg_match('/^([0-6])_([0-5])$/',$rule,$m))continue;$weekday=(int)$m[1];$week=(int)$m[2];mysqli_stmt_bind_param($insert,'iii',$id,$weekday,$week);mysqli_stmt_execute($insert);}mysqli_stmt_close($insert);mysqli_commit($conn);oecrm_audit($conn,'shifts',$id?'update':'create','shift',$id,'Shift saved',null,$_POST);$_SESSION['shift_flash']='Shift saved successfully.';header('Location: shifts.php');exit;}catch(Throwable $e){mysqli_rollback($conn);http_response_code(400);exit($e->getMessage());}
}
if($action==='assign'){
 oecrm_require_permission($conn,'shift_assignments','assign');$employeeId=oecrm_int_param($_POST,'employee_id');$shiftId=oecrm_int_param($_POST,'shift_id');$effective=$_POST['effective_from']??'';$reason=trim($_POST['reason']??'');if(!$effective){http_response_code(400);exit('Effective date is required.');}$actor=(int)$_SESSION['adminId'];$stmt=mysqli_prepare($conn,'SELECT e.company_id employee_company,s.company_id shift_company FROM employeestbl e JOIN shifts s ON s.id=? WHERE e.id=? AND e.status=0 AND s.status=1');mysqli_stmt_bind_param($stmt,'ii',$shiftId,$employeeId);mysqli_stmt_execute($stmt);$match=mysqli_fetch_assoc(mysqli_stmt_get_result($stmt));mysqli_stmt_close($stmt);if(!$match||$match['employee_company']!=$match['shift_company']){http_response_code(400);exit('Employee and shift must belong to the same company.');}
 mysqli_begin_transaction($conn);try{$stmt=mysqli_prepare($conn,'SELECT id,shift_id,effective_from FROM employee_shift_assignments WHERE employee_id=? AND status=1 AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?) ORDER BY effective_from DESC,id DESC LIMIT 1 FOR UPDATE');mysqli_stmt_bind_param($stmt,'iss',$employeeId,$effective,$effective);mysqli_stmt_execute($stmt);$active=mysqli_fetch_assoc(mysqli_stmt_get_result($stmt));mysqli_stmt_close($stmt);$stmt=mysqli_prepare($conn,'SELECT COUNT(*) total FROM employee_shift_assignments WHERE employee_id=? AND status=1 AND effective_from>?');mysqli_stmt_bind_param($stmt,'is',$employeeId,$effective);mysqli_stmt_execute($stmt);$future=mysqli_fetch_assoc(mysqli_stmt_get_result($stmt));mysqli_stmt_close($stmt);if((int)($future['total']??0)>0){throw new RuntimeException('Employee already has a future shift assignment.');}if($active && (int)$active['shift_id']===(int)$shiftId){throw new RuntimeException('This shift is already assigned for the selected date.');}$oldShift=$active?(int)$active['shift_id']:null;if($active){$endDate=date('Y-m-d',strtotime($effective.' -1 day'));$stmt=mysqli_prepare($conn,'UPDATE employee_shift_assignments SET effective_to=?,status=0 WHERE id=?');mysqli_stmt_bind_param($stmt,'si',$endDate,$active['id']);mysqli_stmt_execute($stmt);mysqli_stmt_close($stmt);}$stmt=mysqli_prepare($conn,'INSERT INTO employee_shift_assignments(employee_id,shift_id,effective_from,status,notes,assigned_by) VALUES(?,?,?,1,?,?)');mysqli_stmt_bind_param($stmt,'iissi',$employeeId,$shiftId,$effective,$reason,$actor);mysqli_stmt_execute($stmt);$assignmentId=mysqli_insert_id($conn);mysqli_stmt_close($stmt);$stmt=mysqli_prepare($conn,'INSERT INTO employee_shift_history(employee_id,old_shift_id,new_shift_id,effective_from,reason,changed_by) VALUES(?,?,?,?,?,?)');mysqli_stmt_bind_param($stmt,'iiissi',$employeeId,$oldShift,$shiftId,$effective,$reason,$actor);mysqli_stmt_execute($stmt);mysqli_stmt_close($stmt);mysqli_commit($conn);oecrm_audit($conn,'shift_assignments','assign','shift_assignment',$assignmentId,'Employee shift assigned',['shift_id'=>$oldShift],['shift_id'=>$shiftId,'effective_from'=>$effective]);$_SESSION['shift_flash']='Shift assigned successfully.';header('Location: shiftAssignments.php');exit;}catch(Throwable $e){mysqli_rollback($conn);http_response_code(400);exit($e->getMessage());}
}
if($action==='delete'){
 oecrm_require_permission($conn,'shifts','delete');$id=oecrm_int_param($_POST,'id');$shift=mysqli_fetch_assoc(mysqli_query($conn,'SELECT * FROM shifts WHERE id='.(int)$id));if(!$shift){http_response_code(404);exit('Shift not found.');}$used=mysqli_fetch_assoc(mysqli_query($conn,'SELECT COUNT(*) total FROM employee_shift_assignments WHERE shift_id='.(int)$id.' AND status=1'));if((int)($used['total']??0)>0){mysqli_query($conn,'UPDATE shifts SET status=0 WHERE id='.(int)$id);$_SESSION['shift_flash']='Shift is in use, so it was deactivated instead of deleted.';}else{mysqli_query($conn,'DELETE FROM shift_weekly_off_rules WHERE shift_id='.(int)$id);mysqli_query($conn,'DELETE FROM shifts WHERE id='.(int)$id);$_SESSION['shift_flash']='Shift deleted successfully.';}oecrm_audit($conn,'shifts','delete','shift',$id,'Shift removed',$shift,['deleted'=>1]);header('Location: shifts.php');exit;
}
http_response_code(400);exit('Invalid action.');
